platform :ios, '9.0'
use_frameworks!

target 'FlickrAPITestApp' do
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
end

target 'FlickrAPITestAppTests' do
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
end

target 'FlickrAPITestAppUITests' do
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
end
